[package]
edition = "2021"
name = "openapi-test"
publish = false
version = "0.1.0"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
silent = {path = "../../silent"}
silent-openapi = {path = "../../silent-openapi"}
tokio = {version = "1.0", features = ["full"]}
utoipa = "5"
