[package]
name = "openapi-test"
version = "0.1.0"
edition = "2021"

[dependencies]
silent = { path = "../../silent" }
silent-openapi = { path = "../../silent-openapi" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
utoipa = "4.2"
