[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
which = "6"
serde_json = "1"
chrono = { version = "0.4" }

[dev-dependencies]
