[package]
edition.workspace = true
name = "example-extractors"
publish = false
version = "0.1.0"

[dependencies]
async-trait = {workspace = true}
serde = {workspace = true, features = ["derive"]}
silent = {path = "../../silent"}
tracing.workspace = true
